- name: "restart haproxy"
  service:
    name: haproxy
    state: restarted

- name: "reload haproxy"
  service:
    name: haproxy
    state: reloaded

- name: "daemon reload"
  systemd:
    daemon_reload: "yes"
