ubuntu_distribution:  "bionic"
erlang_version:       "21"
erlang_key_url:       "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"
erlang_repo:          "deb [ arch=amd64 ] https://dl.bintray.com/rabbitmq-erlang/debian {{ ubuntu_distribution }} erlang-{{ erlang_version }}.x"
erlang_packages:
    - "erlang-base"
    - "erlang-asn1"
    - "erlang-crypto"
    - "erlang-eldap"
    - "erlang-ftp"
    - "erlang-inets"
    - "erlang-mnesia"
    - "erlang-os-mon"
    - "erlang-parsetools"
    - "erlang-public-key"
    - "erlang-runtime-tools"
    - "erlang-snmp"
    - "erlang-ssl"
    - "erlang-syntax-tools"
    - "erlang-tftp"
    - "erlang-syntax-tools"
    - "erlang-xmerl"

rabbitmq_version:   ""
rabbitmq_repo:      "deb [ arch=amd64 ] https://dl.bintray.com/rabbitmq/debian {{ ubuntu_distribution }} main"
